name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ğŸ“¦ Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.4 # or your preferred pnpm version

      - name: ğŸ”— Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run formatter
        run: pnpm format

  deploy:
    name: ğŸ§² Pull & Restart on VPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ğŸ” Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts

      - name: ğŸ—ï¸ Pull latest code & rebuild
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_IP: ${{ secrets.VPS_HOST }}
        run: |
          ssh $VPS_USER@$VPS_IP << 'EOF'
            cd htdocs/www.100poweruae.com
            git pull origin master
            rm -rf .next
            source /home/power/.bashrc
            export NODE_ENV=production
            pnpm install
            pnpm run build
            pm2 restart 0
          EOF
